### ISSUE TITLE
Cannot git clone the repository

### ISSUE THREAD

**Issue by shineworld** [Embarcadero/PythonEnvironments#49]
There is some issue in the git clone of the repository:
![image](https://github.com/Embarcadero/PythonEnvironments/assets/1633598/f60a0307-11b4-4210-beca-c96180c91bd2)

I've tried many times, also deleting the current repository and trying a new git clone.
I'm on W10 under fiber internet connection:
>git --version
git version 2.29.2.windows.2

C:\Libraries\lib_embarcadero_1\__repository__\PythonEnvironments>git lfs logs last
git-lfs/2.12.1 (GitHub; windows amd64; go 1.14.10; git 85b28e06)
git version 2.29.2.windows.2

$ git-lfs.exe filter-process
Error downloading object: python/python3-android-3.10.7-arm.zip (dc36384): Smudge error: Error downloading python/python3-android-3.10.7-arm.zip (dc36384cab418e4085f24f36a486887b42a0be0fa740bd01fabf02f700a26620): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response
github.com/git-lfs/git-lfs/errors.newWrappedError
        D:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.Wrap
        D:/a/git-lfs/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
        D:/a/git-lfs/git-lfs/tq/api.go:77
github.com/git-lfs/git-lfs/tq.Batch
        D:/a/git-lfs/git-lfs/tq/api.go:40
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
        D:/a/git-lfs/git-lfs/tq/transfer_queue.go:559
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
        D:/a/git-lfs/git-lfs/tq/transfer_queue.go:453
runtime.goexit
        go/src/runtime/asm_amd64.s:1373
Error downloading python/python3-android-3.10.7-arm.zip (dc36384cab418e4085f24f36a486887b42a0be0fa740bd01fabf02f700a26620)
github.com/git-lfs/git-lfs/errors.newWrappedError
        D:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.Wrapf
        D:/a/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.(*GitFilter).downloadFile
        D:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:115
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
        D:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:76
github.com/git-lfs/git-lfs/commands.smudge
        D:/a/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
        D:/a/git-lfs/git-lfs/commands/command_filter_process.go:120
github.com/spf13/cobra.(*Command).execute
        go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
        go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/commands.Run
        D:/a/git-lfs/git-lfs/commands/run.go:103
main.main
        D:/a/git-lfs/git-lfs/git-lfs.go:33
runtime.main
        go/src/runtime/proc.go:203
runtime.goexit
        go/src/runtime/asm_amd64.s:1373
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
        D:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.NewSmudgeError
        D:/a/git-lfs/git-lfs/errors/types.go:284
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
        D:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:85
github.com/git-lfs/git-lfs/commands.smudge
        D:/a/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
        D:/a/git-lfs/git-lfs/commands/command_filter_process.go:120
github.com/spf13/cobra.(*Command).execute
        go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
        go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/commands.Run
        D:/a/git-lfs/git-lfs/commands/run.go:103
main.main
        D:/a/git-lfs/git-lfs/git-lfs.go:33
runtime.main
        go/src/runtime/proc.go:203
runtime.goexit
        go/src/runtime/asm_amd64.s:1373

Current time in UTC:
2024-01-08 08:35:46

ENV:
LocalWorkingDir=C:\Libraries\lib_embarcadero_1\__repository__\PythonEnvironments
LocalGitDir=C:\Libraries\lib_embarcadero_1\__repository__\PythonEnvironments\.git
LocalGitStorageDir=C:\Libraries\lib_embarcadero_1\__repository__\PythonEnvironments\.git
LocalMediaDir=C:\Libraries\lib_embarcadero_1\__repository__\PythonEnvironments\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Libraries\lib_embarcadero_1\__repository__\PythonEnvironments\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Libraries\lib_embarcadero_1\__repository__\PythonEnvironments\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_ASKPASS=C:\Program Files\TortoiseGit\bin\SshAskPass.exe
GIT_ASK_YESNO=C:\Program Files\TortoiseGit\bin\SshAskPass.exe
GIT_DIR=C:/Libraries/lib_embarcadero_1/__repository__/PythonEnvironments/.git
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_SSH=C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
GIT_SSH_VARIANT=ssh
TGIT_INITIATED_CALL=1

Client IP addresses:
fe80::ac5:c63e:3bde:6275 192.168.0.27
fe80::267b:182e:7bef:aed4 192.168.229.1
fe80::d8f2:79e7:8ec8:a6d5 192.168.244.1

Trying to revert git clone delete files:
![image](https://github.com/Embarcadero/PythonEnvironments/assets/1633598/d86749c0-c573-49ce-898f-b396bcba529a)

**Comment by lmbelo** [comment]
@shineworld we are migrating the Python bundles to a cloud storage. It might be unavailable until we finish this process.

**Comment by lmbelo** [comment]
@shineworld we have just released a new version. Can you check if this issue is gone?

**Comment by shineworld** [comment]
> @shineworld we have just released a new version. Can you check if this issue is gone?

Worked fine :)
![image](https://github.com/Embarcadero/PythonEnvironments/assets/1633598/32ea545a-5394-4cba-8dcd-f68f3e79e115)

**Comment by Basti-Fantasti** [comment]
I had the same issue when checking it out a few weeks back but today cloning the repo was possible without any issues or errors
